### ISSUE TITLE
Map the LiDAR semantic label to KITTI images

### ISSUE THREAD

**Issue by cak0** [PRBonn/semantic-kitti-api#10]
Hi, I am working more on the image domain.
I am interested to map the semantic label from LiDAR points to KITTI image pixels.
Is this function provided by the API? I've been trying to find but might have overlooked.
Many thanks.

**Comment by tano297** [comment]
Hi,

Projecting the points from the point clouds to the image is a purely geometric problem, it has nothing to do with the labels. In the interest of keeping the API simple, we only include things that are relevant to our benchmark. 

I suggest you have a look at [pykitti](https://github.com/utiasSTARS/pykitti) and [this blog post](https://stackoverflow.com/questions/45333780/kitti-velodyne-point-to-pixel-coordinate) to get started on that.

Note: this will project points to the images, which DO NOT cover the entirety of the image pixels, only a subset. Because of this, our labels will also be sparse in the image domain.

**Comment by cak0** [comment]
Thanks for the clarification. I close this issue then.
