### ISSUE TITLE
How is the height of the LiDAR relative to the ground calculated?

### ISSUE THREAD

**Issue by ruanych** [PRBonn/semantic-kitti-api#110]
Thank you for the excellent work.

The heights of the points may contain semantic information about them, so I am interested in the height of the LiDAR relative to the ground. According to [the setup page](https://www.cvlibs.net/datasets/kitti/setup.php) in KITTI, the height of the LiDAR is 1.73m. 
I would like to know if this height refers to the distance from the ground to the bottom or top or center of the LiDAR, and whether SemanticKITTI maintains the same lidar setup as KITTI.

Also, I would like to know the height of the LiDAR itself.

Thank you for your replies!

**Comment by jbehley** [comment]
We "just" labeled the original data from KITTI. So refer to the papers on KITTI (IJRR or CVPR) to maybe get more information about the sensor setup. But also their  website contains more information.

**Comment by Ryyyc** [comment]
I did not find a definition of LIDAR height on the website or in the paper. By common sense, it should be the distance from the ground to the bottom of the lidar. But I am not so sure.

**Comment by jbehley** [comment]
As I have no specific information about the exact location where it's measured, I would suggest contacting Andreas Geiger, since he was involved in the recording of the data. I quickly skimmed over the website and the IJRR paper and the specific location (I would also guess that it's the base/bottom of the scanner) is not mentioned.

**Comment by Ryyyc** [comment]
@jbehley  Thank you for your reply.
