### ISSUE TITLE
How will the Sphere projection change if Lidar height is changed?

### ISSUE THREAD

**Issue by anirudhtopiwala** [PRBonn/semantic-kitti-api#12]
From what I understand the sphere image projection is independent of the height of the lidar right now. What if the height changes, how do you transform the sphere projection? As the sphere image projection formed due to the new height will be very different to what the network has previously seen and trained on.

**Comment by tano297** [comment]
Hi,

The purpose of the API is purely for visualization and evaluation of the results. For this visualization, the fullest spherical projection you can get is by using 64px in height (1 per beam), and taking the center of the sphere in the center of the lidar-scan, so the image projection is, in fact, independent of the height. This is a bit of a double step to obtain something similar to what the raw sensor data already gives you (64 vertical beams rotating, giving you an image-like representation), since we going from raw image-like sensor data, to point cloud, back to image-like data (but deskewed).

Maybe this is more of a question for [lidar-bonnetal](https://github.com/PRBonn/lidar-bonnetal), we can close here and maybe you can reopen there, where the models/height do matter. But as a quick response, if you only train in one height, it is unlikely that the model will work on other data unless you move your new inference data sphere center to the same height as before, or better, retrain using the labels as seen from the new height.
