### ISSUE TITLE
Adding Description to Codalab

### ISSUE THREAD

**Issue by YilmazKadir** [PRBonn/semantic-kitti-api#136]
I submitted my test results to the benchmark. Now, I want to update the description to add the name, pdf url and code url. I have updated the description in Codalab using the format you provided but the information is not present in the leaderboard. What should I do exactly to add description?

**Comment by jbehley** [comment]
I have to have a look into it next week after ICCV. currently no idea, sorry.

**Comment by jbehley** [comment]
I looked now into your zip file that you submitted in the Panoptic4D competition: Your last submission does not contain a "description.txt" as explained in the README of this repository: https://github.com/PRBonn/semantic-kitti-api#validation Therefore the script for generating the detailed results cannot fill in the information.

If you submitted a submission zip-file with a description in the root directory (and the necessary information), then there should be the information in the "detailed results" visible.

Hope that clarifies the issue (if you need to delete a submission due to an error on our side, I can remove the erroneous submission.)

**Comment by YilmazKadir** [comment]
Thank you for the detailed explanation. I tried to edit the description as shown below but it did not show in the benchmark.
![image](https://github.com/PRBonn/semantic-kitti-api/assets/59517677/fb26dcf1-00ac-457d-8bd4-149fe96a42ad)
We needed to have the test results before publishing the paper and we did not have the arxiv link beforehand. I would appreciate it if you could delete the last submission so I can upload it with a description.

**Comment by jbehley** [comment]
just to be clear: the "description.txt" must be part of the zip file.

**Comment by YilmazKadir** [comment]
Thank you for your support. I have uploaded the file with a description and the details are present on the Codalab page. I think you do a manual check before adding it to the leaderboard.
