### ISSUE TITLE
SemanticKITTI Instance Labels

### ISSUE THREAD

**Issue by kelvin95** [PRBonn/semantic-kitti-api#14]
Hi,

Thanks for preparing/releasing this dataset!

Based on the APIs provided, it looks like SemanticKITTI has instance labels. However, this is not described in the paper. Could you speak to what the labeling policy for instance labels is, and if they are reliable for use?

Thanks!
Kelvin

**Comment by jbehley** [comment]
You're right. Surprise! We also provide instance labels for cars, trucks, other-vehicle, pedestrian, bicyclist, bicycle, motorcycle (including moving (!!!) and non-moving objects).

We did not add this to the paper, since the instance labels were added just recently (we might provided numbers and statistics, etc. in a future dataset paper, but we have some more stuff in preparation...). We tried to ensure that instance labels are sequence/temporally consistent. Thus, the same moving object should have the same instance id over time and we visually verified that this is also true for loop closures.

Thus, they should be reliable to use, but let us know if something is still wrong or you notice something odd...

**Comment by kelvin95** [comment]
Great, thanks! This is exciting.

Just to clarify: should I expect all classes under the vehicle and human categories to have instance labels?

**Comment by jbehley** [comment]
yes, all classes in the root categories vehicle and human should have instance ids.

**Comment by kelvin95** [comment]
Great, thanks for the prompt response!

**Comment by bisalgt** [comment]
Thanks for the explanation Jens.
