### ISSUE TITLE
Questions about the instance labels

### ISSUE THREAD

**Issue by Garrison-ctrl** [PRBonn/semantic-kitti-api#147]
Thank you very much for your contribution to the community. After analyzing the dataset, I found that the instance IDs of trunk and pole are 0, is it because only dynamic objects are labeled with instance IDs? Then what exactly are they? If I want to find out which point clouds belong to the same static object, can you provide a corresponding method?

**Comment by jbehley** [comment]
The panoptic labels (i.e., the instance annotations) are actually part of an extension that we made at a later point in time; therefore, information about the instances can be found in our follow-up paper: https://arxiv.org/pdf/2003.02371.pdf

At that point in time, we decided to only include traffic participants as instance labels, i.e., vehicles, pedestrians, and bicyclists; as noted in Sec. III.A: 

![image](https://github.com/PRBonn/semantic-kitti-api/assets/11506664/5b8a0a8b-47b5-4d89-8397-708ac604ae1c)

You can also find information about this in the label definition of the point labeler: https://github.com/jbehley/point_labeler/blob/master/assets/labels.xml

Technically, one can also have poles, etc. as instances, but we decided to not include these into the definition of our dataset. 


Regarding your second question: " If I want to find out which point clouds belong to the same static object, can you provide a corresponding method?" As the poses provide global coordinates for all points, a simple grid-based clustering should be sufficient as we did for static cars in the above-mentioned panoptic segmentation dataset paper: 

![image](https://github.com/PRBonn/semantic-kitti-api/assets/11506664/97a03534-64ce-471f-a585-cbca8f30237b)

We did something in this direction (for the unsupervised instance segmentation paper) -- Therefore, I know that there is still some manual clean-up is still needed (due to closeby objects that can be clustered into a single instance), but these are only a number of minority cases.

**Comment by jbehley** [comment]
I close this issue now; if you have further questions regarding the instance labels, just reopen the issue.

**Comment by jbehley** [comment]
I close this issue now; if you have further questions regarding the instance labels, just reopen the issue.
