### ISSUE TITLE
How to calculate the content section？

### ISSUE THREAD

**Issue by li1997522** [PRBonn/semantic-kitti-api#158]
Hi @jbehley , Thanks for your code! I have a question. I want to use my own dataset to train. But I may change some label in yaml file. I already use your work point_labeler to label my point cloud data. But for the Content part, I have no idea to calculate them. Do you have file to create them? I see this content.py file in this project. But I can't use it. ` 
parsing seq 0
Sequence folder exists!
Labels folder exists!
456
456
Traceback (most recent call last):
  File "./content.py", line 101, in <module>
    scan = SemLaserScan(nclasses, CFG["color_map"], project=False)
TypeError: __init__() got multiple values for argument 'project'
`
They show this error. Do I have other way to get the each part number of point cloud? Thanks for your code again!

**Comment by jbehley** [comment]
The "content" part is just the fraction of data for a specific class calculated over all scans.

The error occurred since there was an additional argument in the constructor that is not needed anymore. I guess that we didn't update this script as it was only used once. Sorry for the confusion.

I guess the `content.py` should now compute the statistics.

**Comment by li1997522** [comment]
It's work! Thanks for your help!
