### ISSUE TITLE
uploading results on the competition

### ISSUE THREAD

**Issue by ayushais** [PRBonn/semantic-kitti-api#16]
Hi,

I tried uploading a zip folder on the competition but it does not upload. Is there a size limit of the zip folder?

**Comment by jbehley** [comment]
as far as i know there is no restriction on the file size, but you should have a zip of around 150-200 mb, since the data is highly redundant and can be therefore quite well compressed.

However, there is currently no indicator on that the upload is still in progress. Thus, you might have just to wait longer especially of you connection is slow. Usually uploading is also much slower then downloading stuff.

Please also use also our verification script to ensure that your submission contains everything.


Let me know if it still doesn't work even though you waited (and stayed on the submission page.)

**Comment by ayushais** [comment]
Hi,

The uploading did not happen because of slow connection. It works now. Thanks

**Comment by jbehley** [comment]
i close now this issue, thanks.
