### ISSUE TITLE
Standard error for submission when submited

### ISSUE THREAD

**Issue by shuangjiexu** [PRBonn/semantic-kitti-api#50]
I submit a result zip tested by `validate_submission.py`  to Codalab, but get 
`Standard error for submission`
in `View scoring error log`, and the status remaining `Submitted`.

Is the issue with Codalab or something else? When can we submit again?

Thanks!

**Comment by jbehley** [comment]
I looked in the recent submission of the competition and could not see anything problematic.

Could you please say which of competition, user, and data, such that I can have a look at the submission.

Currently, I'm not aware of any problem with Codalab, since very recent submissions just got evaluated.

**Comment by shuangjiexu** [comment]
the [SemanticKITTI: Semantic Segmentation competition](https://competitions.codalab.org/competitions/20331)
I try again and submitted successfully.
Thanks!
