### ISSUE TITLE
OXTS/GPS data

### ISSUE THREAD

**Issue by JulesSanchez** [PRBonn/semantic-kitti-api#70]
Hello,

I was wondering if the OXTS/GPS data are available for the specific frames used by Semantic KITTI ? I would be interested in comparing KITTI-360 and SemanticKITTI road taken.

Have a great day

**Comment by jbehley** [comment]
Hi @JulesSanchez,

since we are building upon the KITTI dataset, you can leverage the mapping of the training sequences to the raw sequences, detailed in the devkit of the odometry benchmark (see http://www.cvlibs.net/datasets/kitti/eval_odometry.php) to get the GPS information. For the test set, this information is not available.

Hope that helps.

**Comment by JulesSanchez** [comment]
For next readers,

The mapping of the odometry sequence and the raw data can be found : 
https://github.com/alexkreimer/odometry/blob/master/devkit/readme.txt

After that you can download the data and extract the OXTS. It is a bit tedious but easy.

Have a great day.
