### ISSUE TITLE
Understanding Spherical Projection

### ISSUE THREAD

**Issue by alrzmshy** [PRBonn/semantic-kitti-api#76]
Hello,

I've been trying to understand the spherical projection process. I generated the projection mask for a few scans from sequence 00, scans 0-2:

![00_00](https://user-images.githubusercontent.com/26597554/117797760-ad53a500-b250-11eb-9352-ede573b67bcb.png)

![00_01](https://user-images.githubusercontent.com/26597554/117797790-b5134980-b250-11eb-98c1-2c6c9f1fd543.png)

![00_02](https://user-images.githubusercontent.com/26597554/117797795-b6447680-b250-11eb-8026-b8c2fb7be1f1.png)

I used the following projection parameters: 
``proj_H = 64, proj_W = 2048, proj_fov_up = 3.0, proj_fov_down = -25.0 ``

I can't find an explanation for the empty rows that appear in the image. I also see them in the example image in the readme file of the repo. But when I follow the similar projection procedure (with changing the projection parameters of course) for other lidars, like Ouster 128, I don't see this effect: 
![ouster128](https://user-images.githubusercontent.com/26597554/117800178-2a801980-b253-11eb-8f9f-a7e06a096b6c.png)

What's the reason behind those empty lines in the projected image of Velodyne 64? Is there a better way to do the projection and get rid of them?

Thank you in advance.

**Comment by jbehley** [comment]
hmmm, yes and no. Since the scan is a bit deformed the points will be projected into other bins (there only the nearest return is kept...therefore, your comment with the non-first returns makes sense), but the empty parts are simply empty.

**Comment by alrzmshy** [comment]
Then I'm not sure if I understood your first comment properly. Sorry, I'm new to the lidar world. Could you elaborate on that a bit more, please? 

Also, it seems a bit wasteful to go through these steps if we can directly access the raw lidar data. What I mean is that, we could easily construct he range image with the raw output of the lidar given that we can identify the order of the beams i.e. we know pixel [i,j] corresponds to which beam, etc. As a result, we won't need the spherical projection and also the KNN post-processing step becomes more straightforward.

**Comment by jbehley** [comment]
Regarding the first thing:

KITTI provides only point clouds and in case of the odometry part of the data, these point clouds are modified by adding the motion of the vehicle. The rotation of the LiDAR takes some time and therefore beams are in reality not fired all at the same spatial location if the vehicle moves. This motion is accounted for and the points are transformed accordingly. That's why you can see a spiral-like pattern of the LiDAR point cloud when you see it from above.

And that's right. A rotating LiDAR produces exactly the right format and you can use it like this.

Again, the projection is only needed when we only have a point cloud, like in the case of KITTI odometry dataset.

**Comment by alrzmshy** [comment]
Thank you. I understand better now.
