### ISSUE TITLE
"Moving" Annotations

### ISSUE THREAD

**Issue by abhinavagarwalla** [PRBonn/semantic-kitti-api#80]
On visualizing the annotation for moving vehicles/pedestrians, I observed that some objects are not visibly moving.

- Are vehicles that are stopped while waiting for a red light, marked as moving? In that sense, moving includes objects that are stationary in the frame but can move?
- How were these annotations obtained?

**Comment by jbehley** [comment]
1. Moving corresponds to objects that moved while they are observed. if they stop in between, we label them still as moving.
2. We annotated all points belonging to the same object as moving, when we could observe that the point cloud of the objects gets inconsistent in the aggregated point cloud due to movement.

**Comment by abhinavagarwalla** [comment]
Thank you for your reply. This seems reasonable.
