### ISSUE TITLE
Are the semantic segementation dataset the same as the semantic completion?

### ISSUE THREAD

**Issue by TintinWuNTUEE** [PRBonn/semantic-kitti-api#82]
Since we want to use the panoptic segementation label for semantic completion trainning, are the data the same?Are they just different representations with different label or are they totally different data? Thanks a lot !!

**Comment by jbehley** [comment]
The original data is the same from which the different representations are generated.

The completion data is just a different representation (voxels) instead of points, but the filenames `00000.bin` of the `voxels` directory correspond to the same point cloud in the `velodyne` directory or the `labels` directory. The original data provided the voxels only for every 5th scan. However, we also generate all voxel volumes for each scan, which you can download on our webpage. 

As described in our papers, the voxels are generated from aggregating multiple scans before the actual scan, i.e., for generating `000100.bin` in the `voxels` directory of a sequence, we used the 100 scans before (0, 1, 2, ..., 100) and the corresponding poses to generate a aggregated point cloud that is then cast into a voxel grid, where each voxel is labeled. Find more information on the data format in the README in the zip file.

The labels are also exactly the same.

**Comment by TintinWuNTUEE** [comment]
Thanks a lot !!

**Comment by TimChou-ntu** [comment]
Hi, I'm wondering since the point cloud label provides instance label with segmentation label, whether the completion voxel label also provides instance label with segmentation label? or how could I get it? Thanks a lot!

**Comment by jbehley** [comment]
Currently, we just account for semantic labels in the generation process. Currently, we have no further plans to also provide instance labels for a separate benchmark. However, you can modify the voxelizer to also provide instance labels.
